const InteractiveEnglish = {
  "code": "200",
  "message": "success",
  "data":
    {
      "origintxt":"Los Angeles",
      "destinationtxt": "Xiamen",
      "ttdtxt": "Time To Destination",
      "dfotxt": "Distance From Origin",
      "dtdtxt": "Distance To Destination",
      "altitudetxt": "Altitude",
      "headingtxt": "True Heading",
      "watchtxt": "Watch",
      "moviestxt": "Movies",
      "tvtxt": "TV",
      "mvtxt": "Music Videos",
      "newstxt": "News",
      "sporttxt": "Sports",
      "listentxt": "Listen",
      "musictxt": "Music",
      "abookstxt": "Audio Books",
      "readtxt": "Read",
      "learntxt": "Learn",
      "magazinetxt": "Magazine",
      "newspapertxt": "News Paper",
      "ebookstxt": "e-Books",
      "surftxt": "Surf",
      "playtxt": "Play",
      "maptxt": "Map",
      "shoptxt": "Shop",
      "eattxt": "Eat",
      "kidstxt": "Kids",
      "exptxt": "Experience",
      "abouttxt": "About Xiamen Air",
      "egrettxt": "Egret Club",
      "desttxt": "Destinations",
      "surveytxt": "Survey",
      "talktxt": "Talk",
      "chattxt": "Chat",
      "msgtxt": "Messages",
      "settingstxt": "Settings",
      "callfatxt": "Call Flight Attendant",
      "lighttxt": "Light Control",
      "langtxt": "Languages",
      "helptxt": "Help",
      "hometxt": "Home",
      "connecttxt": "Connect",
      "alerttxt": "Alert",
      "profiletxt": "Profile",
      "feedbacktxt": "Feedback",
      "mymedialibrarytxt": "My Media History",
      "aboutmenutxt": "About",
  	  "hometxt": "Home",
  	  "watchnowtxt":"Watch Now",
  	  "playtrailertxt": "Play Trailer",
  	  "addtowatchlisttxt": "Add To Watchlist",
  	  "descriptiontxt": "Description",
  	  "genrestxt": "Genres",
  	  "directortxt": "Director",
  	  "casttxt": "Cast",
  	  "searchtexttxt": "Please type text to search",
  	  "searchflighttimetxt": "Short than remaining flight time",
  	  "searchaudiolanguagetxt": "Audio track language",
  	  "searchsubtitlelanguagetxt": "Subtitle language",
  	  "searchgenrestxt": "Genres",
  	  "searchuserratingstxt": "User ratings",
  	  "searchtxt": "Search",
  	  "searchresultstxt": "Search results",
  	  "searchfoundtxt": "found"
    }
}


module.exports = {InteractiveEnglish};
