const InteractiveChinese = {
  "code": "200",
  "message": "success",
  "data":
    {
      "origintxt": "洛杉矶",
      "destinationtxt": "厦门",
      "ttdtxt": "剩余飞行时间",
      "dfotxt": "离出发地距离",
      "dtdtxt": "到目的地距离",
      "altitudetxt": "高度",
      "headingtxt": "航向",
      "watchtxt": "观看",
      "moviestxt": "电影",
      "tvtxt": "电视",
      "mvtxt": "音乐电视",
      "newstxt": "新闻",
      "sporttxt": "体育",
      "listentxt": "收听",
      "musictxt": "音乐",
      "abookstxt": "有声读物",
      "readtxt": "阅读",
      "magazinetxt": "杂志",
      "newspapertxt": "报纸",
      "ebookstxt": "电子书",
      "surftxt": "上网",
      "playtxt": "品玩",
      "maptxt": "地图",
      "shoptxt": "购物",
      "eattxt": "餐饮",
      "kidstxt": "儿童",
      "exptxt": "体验",
      "abouttxt": "关于厦门航空",
      "egrettxt": "白鹭俱乐部",
      "desttxt": "目的地信息",
      "surveytxt": "调查问卷",
      "talktxt": "通讯",
      "chattxt": "聊天",
      "msgtxt": "消息",
      "settingstxt": "设置",
      "callfatxt": "请求帮助",
      "lighttxt": "灯光控制",
      "langtxt": "语言",
      "helptxt": "帮助",
      "hometxt": "首页",
      "connecttxt": "上网",
      "alerttxt": "提醒",
      "profiletxt": "个人档案",
      "feedbacktxt": "意见和反馈",
      "mymedialibrarytxt": "浏览记录",
      "aboutmenutxt": "关于"
    }
}

module.exports = {InteractiveChinese};
