const searchList = {
    "code": "200",
    "message": "success",
    "movies": [
      {
        "mid": "10010",
        "posterImageURL": "images/media/poster/10010.jpg",
        "synopsisImageURL": "images/media/synopsis/10010.jpg",
        "videoURL": "./videos/10010.mp4",
        "title": "Operation Red Sea",
        "year": "2018",
        "rating": "NR",
        "description": "PLA Navy Marine Corps launch a hostage rescue operation in Ihwea and undergo a fierce battle with rebellions and terrorism.",
        "audiotracks": "en, ch",
        "closedcaption": "en",
        "subtitles": "en, ch",
        "trailorURL": "./videos/trailor/10010.mp4",
        "duration": "142 min",
        "director": "Dante Lam",
        "cast": "Zhang Hanyu, Zhang Yi, Hai Qing, Du Jiang, Johnny Huang",
        "userrating": "4.5",
        "genres": "Action, Drama, Thriller, War"
      },
      {
        "mid": "10011",
        "posterImageURL": "images/media/poster/10011.jpg",
        "synopsisImageURL": "images/media/synopsis/10011.jpg",
        "videoURL": "./videos/10011.mp4",
        "title": "Detective Chinatown 2",
        "year": "2018",
        "rating": "R",
        "description": "Driven by the desire for the huge reward, Tang Ren (by Wang Baoqiang) tricked Qin Feng (by Liu Haoran) to New York, to attend the World Detective Contest,. Later on, behind the crazy competition, Qin and Tang discovered the real hidden facts of this contest.",
        "audiotracks": "en, ch",
        "closedcaption": "en",
        "subtitles": "en, ch",
        "trailorURL": "./videos/trailor/10011.mp4",
        "duration": "121 min",
        "director": "Sicheng Chen",
        "cast": "Haoran Liu, Baoqiang Wang, Yang Xiao",
        "userrating": "4.8",
        "genres": "Action, Comedy"
      },
      {
        "mid": "10012",
        "posterImageURL": "images/media/poster/10012.jpg",
        "synopsisImageURL": "images/media/synopsis/10012.jpg",
        "videoURL": "./videos/sample.mp4",
        "title": "The Godfather",
        "year": "1972",
        "rating": "R",
        "description": "As the remnants of the Resistance flee Kylo Ren and the First Order, Rey seeks out Luke Skywalker -- but he wants nothing more to do with the Force.",
        "audiotracks": "en, ch",
        "closedcaption": "en",
        "subtitles": "en",
        "trailorURL": "./videos/trailor.mp4",
        "duration": "01:45:12",
        "director": "Rian Johnson",
        "cast": "Mark Hamill,Carrie Fisher,Adam Driver",
        "userrating": "3.0",
        "genres": "Action &amp; Adventure"
      },
      {
        "mid": "10013",
        "posterImageURL": "images/media/poster/10013.jpg",
        "synopsisImageURL": "images/media/synopsis/10013.jpg",
        "videoURL": "./videos/sample.mp4",
        "title": "The Dark Knight",
        "year": "2008",
        "rating": "PG",
        "description": "As the remnants of the Resistance flee Kylo Ren and the First Order, Rey seeks out Luke Skywalker -- but he wants nothing more to do with the Force.",
        "audiotracks": "en",
        "closedcaption": "",
        "subtitles": "en",
        "trailorURL": "./videos/trailor.mp4",
        "duration": "00:57:10",
        "director": "Rian Johnson",
        "cast": "Mark Hamill,Carrie Fisher,Adam Driver",
        "userrating": "3.0",
        "genres": "Action &amp; Adventure"
      },
      {
        "mid": "10014",
        "posterImageURL": "images/media/poster/10014.jpg",
        "synopsisImageURL": "images/media/synopsis/10014.jpg",
        "videoURL": "./videos/sample.mp4",
        "title": "The Godfather: Part II",
        "year": "1974",
        "rating": "R",
        "description": "As the remnants of the Resistance flee Kylo Ren and the First Order, Rey seeks out Luke Skywalker -- but he wants nothing more to do with the Force.",
        "audiotracks": "en, ch, ko",
        "closedcaption": "ch",
        "subtitles": "en, ko",
        "trailorURL": "./videos/trailor.mp4",
        "duration": "01:15:00",
        "director": "Rian Johnson",
        "cast": "Mark Hamill,Carrie Fisher,Adam Driver",
        "userrating": "3.0",
        "genres": "Action &amp; Adventure"
      },
      {
        "mid": "10015",
        "posterImageURL": "images/media/poster/10015.jpg",
        "synopsisImageURL": "images/media/synopsis/10015.jpg",
        "videoURL": "./videos/sample.mp4",
        "title": "Pulp Fiction",
        "year": "1994",
        "rating": "R",
        "description": "As the remnants of the Resistance flee Kylo Ren and the First Order, Rey seeks out Luke Skywalker -- but he wants nothing more to do with the Force.",
        "audiotracks": "en, sp",
        "closedcaption": "en",
        "subtitles": "en, sp",
        "trailorURL": "./videos/trailor.mp4",
        "duration": "02:10:00",
        "director": "Rian Johnson",
        "cast": "Mark Hamill,Carrie Fisher,Adam Driver",
        "userrating": "3.0",
        "genres": "Crime, Fiction"
      },
      {
        "mid": "10016",
        "posterImageURL": "images/media/poster/10016.jpg",
        "synopsisImageURL": "images/media/synopsis/10016.jpg",
        "videoURL": "./videos/sample.mp4",
        "title": "The Lord of the Rings: The Return of the King",
        "year": "2003",
        "rating": "PG-13",
        "description": "As the remnants of the Resistance flee Kylo Ren and the First Order, Rey seeks out Luke Skywalker -- but he wants nothing more to do with the Force.",
        "audiotracks": "en, ch",
        "closedcaption": "en",
        "subtitles": "en, ch",
        "trailorURL": "./videos/trailor.mp4",
        "duration": "01:30:00",
        "director": "Rian Johnson",
        "cast": "Mark Hamill,Carrie Fisher,Adam Driver",
        "userrating": "3.0",
        "genres": "Sci-Fiction, Children &amp; Family Movies"
      },
      {
        "mid": "10017",
        "posterImageURL": "images/media/poster/10017.jpg",
        "synopsisImageURL": "images/media/synopsis/10011.jpg",
        "videoURL": "./videos/sample.mp4",
        "title": "Inception",
        "year": "2010",
        "rating": "PG-13",
        "description": "As the remnants of the Resistance flee Kylo Ren and the First Order, Rey seeks out Luke Skywalker -- but he wants nothing more to do with the Force.",
        "audiotracks": "en, ch, th",
        "closedcaption": "en",
        "subtitles": "en, ch, th",
        "trailorURL": "./videos/trailor.mp4",
        "duration": "01:20:30",
        "director": "Rian Johnson",
        "cast": "Mark Hamill,Carrie Fisher,Adam Driver",
        "userrating": "3.0",
        "genres": "Action &amp; Adventure, Children &amp; Family Movies"
      },
      {
        "mid": "10018",
        "posterImageURL": "images/media/poster/10018.jpg",
        "synopsisImageURL": "images/media/synopsis/10018.jpg",
        "videoURL": "./videos/sample.mp4",
        "title": "Forrest Gump",
        "year": "1994",
        "rating": "PG-13",
        "description": "As the remnants of the Resistance flee Kylo Ren and the First Order, Rey seeks out Luke Skywalker -- but he wants nothing more to do with the Force.",
        "audiotracks": "en, sp",
        "closedcaption": "en",
        "subtitles": "",
        "trailorURL": "./videos/trailor.mp4",
        "duration": "01:45:12",
        "director": "Rian Johnson",
        "cast": "Mark Hamill,Carrie Fisher,Adam Driver",
        "userrating": "3.0",
        "genres": "Children &amp; Family Movies"
      },
      {
        "mid": "10019",
        "posterImageURL": "images/media/poster/10019.jpg",
        "synopsisImageURL": "images/media/synopsis/10013.jpg",
        "videoURL": "./videos/sample.mp4",
        "title": "Fight Club",
        "year": "1999",
        "rating": "R",
        "description": "As the remnants of the Resistance flee Kylo Ren and the First Order, Rey seeks out Luke Skywalker -- but he wants nothing more to do with the Force.",
        "audiotracks": "en, ch",
        "closedcaption": "en",
        "subtitles": "en",
        "trailorURL": "./videos/trailor.mp4",
        "duration": "00:57:10",
        "director": "Rian Johnson",
        "cast": "Mark Hamill,Carrie Fisher,Adam Driver",
        "userrating": "3.0",
        "genres": "Action &amp; Adventure"
      },
      {
        "mid": "10020",
        "posterImageURL": "images/media/poster/10020.jpg",
        "synopsisImageURL": "images/media/synopsis/10020.jpg",
        "videoURL": "./videos/sample.mp4",
        "title": "Goodfellas",
        "year": "1990",
        "rating": "R",
        "description": "As the remnants of the Resistance flee Kylo Ren and the First Order, Rey seeks out Luke Skywalker -- but he wants nothing more to do with the Force.",
        "audiotracks": "en",
        "closedcaption": "en",
        "subtitles": "en",
        "trailorURL": "./videos/trailor.mp4",
        "duration": "01:15:00",
        "director": "Rian Johnson",
        "cast": "Mark Hamill,Carrie Fisher,Adam Driver",
        "userrating": "3.0",
        "genres": "Crime, Drama"
      },
      {
        "mid": "10021",
        "posterImageURL": "images/media/poster/10021.jpg",
        "synopsisImageURL": "images/media/synopsis/10021.jpg",
        "videoURL": "./videos/sample.mp4",
        "title": "Interstellar",
        "year": "2014",
        "rating": "PG-13",
        "description": "As the remnants of the Resistance flee Kylo Ren and the First Order, Rey seeks out Luke Skywalker -- but he wants nothing more to do with the Force.",
        "audiotracks": "ch, ko",
        "closedcaption": "en",
        "subtitles": "en",
        "trailorURL": "./videos/trailor.mp4",
        "duration": "02:10:00",
        "director": "Christopher Nolan",
        "cast": "Matthew McConaughey, Anne Hathaway, Jessica Chastain, Mackenzie Foy",
        "userrating": "3.0",
        "genres": "Action &amp; Adventure, Children &amp; Family Movies"
      }
    ],
    "data": [
      {
        "cid": "100",
        "name": "Search results",
        "total": "1234",
        "current": "200",
        "movielist": [
          10010,
          10011,
          10012,
          10013,
          10014,
          10015,
          10016,
          10017,
          10018,
          10019,
          10020,
          10021
        ]
      }
    ]
}

module.exports = {searchList};
